apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"generation":15,"labels":{"app":"es-mmon","elasticsearch":"cluster"},"name":"es-mon","namespace":"teste-hml"},"spec":{"podManagementPolicy":"OrderedReady","replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"es-mon","elasticsearch":"cluster"}},"serviceName":"es-mon","template":{"metadata":{"labels":{"app":"es-mon","elasticsearch":"cluster"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"elasticsearch","operator":"In","values":["cluster"]}]},"namespaces":["teste-hml"],"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"env":[{"name":"cluster.name","value":"es-cluster"},{"name":"discovery.seed_hosts","value":"es-mon.teste-hml.svc"},{"name":"cluster.initial_master_nodes","value":"es-mon-0,
      es-mon-1,
      es-mon-2"},{"name":"discovery.zen.minimum_master_nodes","value":"2"},{"name":"gateway.recover_after_nodes","value":"2"},{"name":"ES_JAVA_OPTS","value":"-Xms6g
      -Xmx6g"},{"name":"path.repo","value":"/backup"}],"image":"docker-registry.default.svc:5000/openshift/elasticsearch:7.9.3","imagePullPolicy":"IfNotPresent","name":"es-cluster-node","ports":[{"containerPort":9200,"name":"restapi","protocol":"TCP"},{"containerPort":9300,"name":"transport","protocol":"TCP"}],"resources":{"limits":{"cpu":"4","memory":"8Gi"},"requests":{"cpu":"1","memory":"1536Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/elasticsearch/data","name":"es-storage-db-hml"},{"mountPath":"/backup","name":"es-backup-hml-nfs-volume2"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"node-role.kubernetes.io/compute":"true"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"es-storage-db-hml"},{"name":"es-backup-hml-nfs-volume2","persistentVolumeClaim":{"claimName":"es-backup-hml-nfs-claim2"}}]}},"updateStrategy":{"type":"RollingUpdate"},"volumeClaimTemplates":[{"metadata":{"name":"es-storage-db-hml"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"glusterfs-storage-block"}}]}}
  generation: 4
  labels:
    app: es-mmon
    elasticsearch: cluster
  name: es-mon
  namespace: teste-hml
  selfLink: /apis/apps/v1/namespaces/teste-hml/statefulsets/es-mon
  uid: de7fd916-8e3e-11eb-b8c0-005056b735d5
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: es-mon
      elasticsearch: cluster
  serviceName: es-mon
  template:
    metadata:
      labels:
        app: es-mon
        elasticsearch: cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: elasticsearch
                      operator: In
                      values:
                        - cluster
                namespaces:
                  - teste-hml
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: cluster.name
              value: es-cluster
            - name: discovery.seed_hosts
              value: es-mon.teste-hml.svc
            - name: cluster.initial_master_nodes
              value: 'es-mon-0, es-mon-1, es-mon-2'
            - name: discovery.zen.minimum_master_nodes
              value: '2'
            - name: gateway.recover_after_nodes
              value: '2'
            - name: ES_JAVA_OPTS
              value: '-Xms6g -Xmx6g'
            - name: path.repo
              value: /backup
          image: 'docker-registry.default.svc:5000/openshift/elasticsearch:7.9.3'
          imagePullPolicy: IfNotPresent
          name: es-cluster-node
          ports:
            - containerPort: 9200
              name: restapi
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 8Gi/
            requests:
              cpu: '1'
              memory: 1536Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-storage-db-hml
            - mountPath: /backup
              name: es-backup-hml-nfs-volume2
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/compute: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: es-storage-db-hml
        - name: es-backup-hml-nfs-volume2
          persistentVolumeClaim:
            claimName: es-backup-hml-nfs-claim2
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: es-storage-db-hml
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: glusterfs-storage-block